feat(callout-update): update callout component UI
twilio-labs/paste pull request #2039
Opened 2021-11-15 18:24 UTC by zahnster

* Updates visual appearance
* Cleans up variant naming

2021-11-15 23:48 UTC, shleewhite approved these changes
This looks good! I remember there was talk that this component would need to support both React children and markdown. Is that still needed?

2021-11-16 01:25 UTC, loreina reviewed
Yay, this is looking so awesome!!!! Just a few lil notes:

- The `Callout` on the Object Details patterns page has text that isn't using `color-text-neutral`, but the other `Callout` using the info variant have that text color
![image](https://user-images.githubusercontent.com/23108291/141878191-2d2c3d48-ebe7-40ed-8f88-3be60c3cde5f.png)
- Could we center align the icon when there's no title? It looks a bit higher atm than when there's a title
![image](https://user-images.githubusercontent.com/23108291/141878766-51506567-43a9-4288-949f-3f5c19ae5e57.png)
- Would we want to add stories for Callout without a title? Is that a common use case?

2021-11-16 16:57 UTC, katieporter commented
This is looking amazing! Loreina covered nearly everything, I just noticed a couple more small things:
- When there is more than one paragraph in a callout, none of the paragraphs have a bottom margin. It's perfect that the last paragraph doesn't have a bottom margin, but ideally any other paragraphs would maintain the default margin.
![image](https://user-images.githubusercontent.com/5374045/142027271-e2367077-61de-47f3-8539-49df030ffe85.png)
- The callouts on the /components, /primitives, and /layout pages also use `color-text` instead of `color-text-neutral`. They also have extra margin at the bottom because of the built in margin on List. Not sure if we can fix that in the Callout component, but if we can, it'd be great to remove that margin.
- There are also callouts on /patterns/notifications-and-feedback and /patterns/object-details that have the same problem with the text color. Seems like this happens when using the Paragraph or List components instead of using Text. Not sure if there's a great solution for that or if we just need to clean up those instances to use Text instead?


I do have a tiny request and if it's out of scope, that is totally fine. There are some copy tweaks I'd like to make to callouts to make them feel a little more polished:
- We have some callouts titled "Hot accessibility tip". That's, erm, not super on brand lol. Could we update those to just say "Accessibility insight"?
- We have some callouts that use kind of 🚨aggressive emojis🚨 in the title. Could we run a find and replace on the 🚨 emoji and delete all instances of it? It seems extra aggressive now that we've added the warning icon to the warning callout. We've also got one that uses the 🦮  emoji which is cute but looks a little funny now.

2021-11-16 20:45 UTC, nkrantz commented
I know it technically passes contrast ratio... but do we _like_ it? It's so blue and kind of hurts my eyes but that could totally just be me.
<img width="988" alt="Screen Shot 2021-11-16 at 1 00 58 PM" src="https://user-images.githubusercontent.com/75342690/142040288-9d6d3749-bfd7-4195-817e-2979ad6d8f31.png">

2021-11-19 19:55 UTC, shleewhite requested changes
Sorry for the late review - realized there were some incorrect heading levels.

2021-11-19 19:55 UTC, shleewhite commented on packages/paste-website/src/pages/components/combobox/index.mdx
> +  <CalloutTitle>Power user move!</CalloutTitle>
The heading levels are incorrect here, should be an H5

2021-11-19 19:55 UTC, shleewhite commented on packages/paste-website/src/pages/components/index.mdx
>    <CalloutTitle as="h4">Don't see a component, primitive, or layout you need listed here?</CalloutTitle>
Should be H2

2021-11-19 19:55 UTC, shleewhite commented on packages/paste-website/src/pages/layout/index.mdx
>  <Callout>
Should be H2

2021-11-19 19:55 UTC, shleewhite commented on packages/paste-website/src/pages/patterns/button-vs-anchor/index.mdx
> +  <CalloutTitle>This is not a variant we recommend you use often.</CalloutTitle>
Should be H4

2021-11-19 19:55 UTC, shleewhite commented on packages/paste-website/src/pages/patterns/button-vs-anchor/index.mdx
> +  <CalloutTitle>This is not a variant we recommend you use often.</CalloutTitle>
Should be H4

2021-11-19 19:55 UTC, shleewhite commented on packages/paste-website/src/pages/patterns/object-details/index.mdx
>    <CalloutTitle>Composing a Description List</CalloutTitle>
Should be H4

2021-11-19 19:55 UTC, shleewhite commented on packages/paste-website/src/pages/patterns/object-details/index.mdx
>    <CalloutTitle>This pattern is coming soon!</CalloutTitle>
Should be H4

2021-11-19 19:55 UTC, shleewhite commented on packages/paste-website/src/pages/primitives/index.mdx
>    <CalloutTitle as="h4">Don't see a primitive, layout, or component you need listed here?</CalloutTitle>
Should be H2

2021-11-19 23:20 UTC, zahnster commented
> I know it technically passes contrast ratio... but do we _like_ it? 

Ehh, but I figure that is part of the dark mode color effort in general, there are theming updates on deck there.

2021-11-19 23:30 UTC, shleewhite approved these changes
🚢

2021-11-23 17:19 UTC, katieporter commented
This is pretty minor, so if it's a pain to fix, it's not a huge deal. I noticed that any callout with a UL in it is now very indented. Is it possible to get those to match the indentation of the List component? If not, totally fine.
![image](https://user-images.githubusercontent.com/5374045/143071630-19b2c8ce-498e-41de-8fb9-cb5b57820210.png)

I found one more Callout that still has `color-text` on the Notification and feedback pattern page. I assume it's due to how that individual callout was composed?
![image](https://user-images.githubusercontent.com/5374045/143072087-d1375f19-07b0-4a57-895a-4f7fe36dc124.png)

It looks like all paragraph text within a callout has a margin bottom now, which makes the spacing around the callout look a touch uneven. Is it possible to remove the margin bottom from the _last_ element in any callout?
![image](https://user-images.githubusercontent.com/5374045/143072560-9e80658d-9c06-4271-bf96-a16ae7afa1e0.png)

2021-11-24 01:48 UTC, SiTaggart approved these changes
This feels like a much nicer API 🎉

2021-11-24 16:29 UTC, merged