chore(website): upgrade to Docsearch v3
twilio-labs/paste pull request #2197
Opened 2022-02-09 05:06 UTC by SiTaggart

The version of docsearch we use is being deprecated and we need to migrate to Docsearch v3. This has an entirely new crawler and set up.

2022-02-09 19:58 UTC, TheSisb approved these changes
Looks solid to me

2022-02-10 23:46 UTC, serifluous requested changes

2022-02-10 23:46 UTC, serifluous commented on packages/paste-website/src/styles/docSearch.ts
> +      '--docsearch-key-gradient': theme.backgroundColors.colorBackgroundStrong,
Can you make this colorBackground instead? Contrast on the key shortcut is pretty `bad` right now in dark theme.

2022-02-10 23:46 UTC, serifluous commented on packages/paste-website/src/styles/docSearch.ts
> +      '--docsearch-spacing': theme.space.space60,
Change to space50 so the search icon in the modal isn't so far away from the border.

As far as I can tell, the other stuff that this variable touches is ok if the spacing is bumped down.

2022-02-11 17:54 UTC, serifluous approved these changes

2022-02-15 02:47 UTC, merged