build: add React18 Support
twilio-labs/paste pull request #2682
Opened 2022-09-20 12:49 UTC by andreasonny83

Update packages dependencies to include React v18

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

2022-09-20 17:48 UTC, TheSisb commented
Hey @andreasonny83, thanks for taking this initiative!

Heads up, our `@twilio-paste/uid-library` [may fail in React 18](https://github.com/thearnica/react-uid#readme): 

![image](https://user-images.githubusercontent.com/1592327/191326440-2c260e78-6a19-4465-990d-83c5a3f1d71b.png)


The good news is that we wrap `react-uid` in our own `uid-library` package, so we can fix this is a non-breaking patch change by [changing what we export](https://github.com/twilio-labs/paste/blob/main/packages/paste-libraries/uid/src/index.tsx) to something like this:

```js
const useUID = React.useId; // Use react 18's useId() hook
const useUIDSeed = (item: any) => React.useId(); // Function that calls React useId();
const UIDFork = ({children}) => <>{children}</>; // Do nothing
const uid = (item: any, index?: number) => React.useId(); // Just use React.useId() again
```

I _think_ this would just work, but we'd need to verify in tests and our website/storybook builds.

2022-09-21 18:10 UTC, espipj requested changes
Prefix and Suffix files also need changing in L17 to be:
`const Prefix = React.forwardRef<HTMLDivElement, React.PropsWithChildren<PrefixProps>>(
`
path: `packages/paste-core/components/input-box/src/Prefix.tsx`

Still a problem in props like `insertAfter` in InputBox....

2022-09-21 18:10 UTC, espipj commented on packages/paste-core/components/input-box/src/InputBox.tsx
> +const InputBox = React.forwardRef<HTMLDivElement, React.PropsWithChildren<InputBoxProps>>(
As we're using React.Props**WithChildren** InputBox will have already the children prop. No need to define children on the InputBoxProps L11

2022-09-22 14:11 UTC, espipj requested changes
Btw running `yarn install` with a clean project has updated my `yarn.lock` file... which I guess is because it needs to be updated in the repo too... 😃

2022-10-24 22:07 UTC, TheSisb commented
We need to upgrade our underlying Modal library for React 18 support https://github.com/reach/reach-ui/issues/972

2022-11-30 17:45 UTC, merged