[WIP]feat: add File Uploader component
twilio-labs/paste pull request #2908
Opened 2022-12-29 02:01 UTC by shleewhite

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [ ] I acknowledge that all my contributions will be made under the project's license.

2023-01-03 18:20 UTC, Niznikr commented on packages/paste-website/src/pages/components/file-uploader/index.mdx
> +There are various drag and drop technologies that don’t include accessible solutions (like [ReactDnD](https://github.com/react-dnd/react-dnd/issues/3310), for example) so please take the time to ensu
praise: love these guidelines!

2023-01-03 18:35 UTC, Niznikr commented
When I drag over the icon or drop zone text the drop highlight goes away. This makes it unclear if my action was successful.

https://user-images.githubusercontent.com/2147624/210419567-f457a58c-edd4-468f-8668-8b3fa032949f.mov

2023-01-03 20:17 UTC, nkrantz reviewed
It's so good Lee!! I also noticed the hover issue on drag that Robb mentioned. Just a couple tiny suggestions other than that.

2023-01-03 20:17 UTC, nkrantz commented on packages/paste-website/src/pages/components/file-uploader/index.mdx
> +  FileUploaderDropzoneText,
Could we include FileUploaderItemList and FileUploaderItem here in case users scroll straight down to the usage section

2023-01-03 21:21 UTC, shleewhite commented on packages/paste-core/components/file-uploader/src/FileUploaderDropzone.tsx
> +        element={element}
I like that idea a lot, have we done that on other components before?

2023-01-03 22:06 UTC, nkrantz commented on packages/paste-core/components/file-uploader/src/FileUploaderDropzone.tsx
> +        element={element}
[Switch](https://github.com/twilio-labs/paste/blob/main/packages/paste-core/components/switch/src/SwitchKnob.tsx) does it that way, but it also looks like some other components don't do it that way

2023-01-04 14:42 UTC, kelseycavitt requested changes
@shleewhite I'm leaving some comments on specific design changes in Chromatic. I found just a couple of a differences between the design spec and the implementation. Let me know if you have questions.

2023-01-05 14:06 UTC, Niznikr approved these changes
Excellent work on this!

2023-01-05 19:09 UTC, nkrantz approved these changes

2023-01-06 14:44 UTC, kelseycavitt approved these changes
Looks great!

2023-01-06 14:48 UTC, Niznikr approved these changes

2023-01-06 18:42 UTC, merged