Update avatar styles
twilio-labs/paste pull request #3021
Opened 2023-02-07 00:25 UTC by shleewhite

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [ ] I acknowledge that all my contributions will be made under the project's license.

2023-02-08 01:02 UTC, serifluous requested changes

2023-02-08 01:02 UTC, serifluous commented on packages/paste-core/components/avatar/src/index.tsx
> +    borderColor: 'colorBorderUser',
todo: Avatars need to use shadow borders to align in height with other components (buttons, etc).

See work breakdown doc: https://docs.google.com/document/d/1YDt4_TEcBNT0RqQwAVL_APMkDnMRf5YAy4eW9UttXxQ/edit#bookmark=id.ju18wvpkllnr

2023-02-08 02:01 UTC, serifluous approved these changes

2023-02-08 18:21 UTC, nkrantz approved these changes
Same here, maybe scrap the anatomy section of the docs but otherwise looks good

2023-02-08 18:23 UTC, gloriliale approved these changes

2023-02-09 00:55 UTC, gloriliale approved these changes

2023-02-09 22:19 UTC, libertycarlin approved these changes
lgtm!

2023-02-09 22:52 UTC, gloriliale approved these changes

2023-02-10 20:08 UTC, libertycarlin approved these changes

2023-02-10 20:09 UTC, Niznikr approved these changes

2023-02-10 20:10 UTC, merged