feat: pills and checkboxes and radios
twilio-labs/paste pull request #3060
Opened 2023-02-28 22:17 UTC by SiTaggart

- feat: update checkbox and radio styles for One Twilio
- feat: update display pill group for One Twilio design language
- feat(form-pill-group): update the styles for One Twilio Design Updates

Description and useful links to discussions / issues / tickets

## Changes in this PR:

### Change One

Details of change...

### Change Two

Details of change...

## Checklist

- [ ] Work in a "Draft" branch whilst you are getting feedback to reduce Chromatic costs. Once you are ready for approval, convert the PR to "Ready to review"
- [ ] Ensure all `required` checks have passed
- [ ] Icon changes must have a product design review
- [ ] Website content changes must have a product design review
- [ ] At least two engineers have reviewed any code changes
- [ ] At least one engineering lead has reviewed any core package changes or repository infrastructure
- [ ] Website visual regression testing is run by adding `🕵🏻‍♀️ Run website visual regression` label

2023-03-06 23:50 UTC, loreina requested changes
main design changes to address:
- display pill group should switch to use `fontWeightMedium` - I'll note this in a design ticket to update in figma
- ~~switch box is smaller now, refer to figma or the work breakdown~~ never mind, switch is in another PR

2023-03-07 16:00 UTC, loreina approved these changes

2023-03-07 17:38 UTC, loreina approved these changes

2023-03-07 17:44 UTC, nkrantz approved these changes

2023-03-07 18:44 UTC, merged