fix(toast): remove console patch prop and add left prop
twilio-labs/paste pull request #3081
Opened 2023-03-09 01:11 UTC by nkrantz

### JIRA tickets
[DSYS-3818](https://issues.corp.twilio.com/browse/DSYS-3818)
[DSYS-3646](https://issues.corp.twilio.com/browse/DSYS-3646)

### In this PR
- Removes Toast's Console z-index patch prop added in #1287 (major change)
- Adds a `left` prop to ToastContainer, ToastPortal, and Toaster to fix #3024

2023-03-10 17:02 UTC, SiTaggart requested changes

2023-03-10 17:36 UTC, nkrantz commented on packages/paste-website/src/pages/components/toast/index.mdx
> +id: 'custom_id',
weird. fixed

2023-03-10 21:45 UTC, SiTaggart approved these changes

2023-03-14 02:05 UTC, loreina approved these changes

2023-03-14 17:05 UTC, merged