chore(side modal, file uploader, file picker, pagination): update styles
twilio-labs/paste pull request #3083
Opened 2023-03-09 19:51 UTC by nkrantz

2023-03-10 17:56 UTC, libertycarlin submitted a review, later dismissed
lgtm!

2023-03-10 23:10 UTC, SiTaggart approved these changes

2023-03-13 14:52 UTC, loreina requested changes
noted changes in chromatic

2023-03-14 20:15 UTC, libertycarlin approved these changes

2023-03-14 20:42 UTC, loreina approved these changes

2023-03-14 21:21 UTC, SiTaggart approved these changes

2023-03-14 22:04 UTC, merged