feat(website): add june newsletter
twilio-labs/paste pull request #3270
Opened 2023-06-08 21:05 UTC by nkrantz

2023-06-09 19:31 UTC, serifluous requested changes

2023-06-09 19:31 UTC, serifluous commented on packages/paste-website/src/pages/blog/2023-05-16-paste-newsletter.mdx
> +export const meta = {
chore: The file name needs to change to link appropriately from this page: https://deploy-preview-3270--paste-docs.netlify.app/blog

2023-06-09 19:31 UTC, serifluous commented on packages/paste-website/src/assets/images/articles/2023-06-12-paste-newsletter/tabs.png
This Tabs screenshot has an extra line under "Internet of things". Where'd you pull it from? Is there a bug somewhere?

2023-06-12 18:24 UTC, serifluous approved these changes

2023-06-12 20:51 UTC, SiTaggart approved these changes

2023-06-13 19:42 UTC, merged