chore: remove prop-types
twilio-labs/paste pull request #3442
Opened 2023-08-24 16:57 UTC by TheSisb

Removes all prop-types in every component

2023-08-29 21:12 UTC, nkrantz commented on packages/paste-core/core-bundle/progress-bar/package.json
> +{
sneaky rebase

2023-08-29 22:34 UTC, TheSisb commented on packages/paste-core/core-bundle/progress-bar/package.json
> +{
Doh

2023-09-20 15:46 UTC, SiTaggart approved these changes

2023-09-20 16:24 UTC, SiTaggart requested changes

2023-09-20 16:24 UTC, SiTaggart commented on tools/plop-templates/package.hbs
> +    ,
issue: looks like a whoopsie

2023-09-20 16:30 UTC, TheSisb commented on tools/plop-templates/package.hbs
> +    ,
fixed, good catch.

2023-09-20 17:04 UTC, merged