fix(website):Support and training changes WIP
twilio-labs/paste pull request #962
Opened 2020-11-20 17:13 UTC by ctecks

Added link to training resource. Removed duplication. Added info on office hours expectations.

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [ ] I acknowledge that all my contributions will be made under the project's license.

2020-12-11 16:20 UTC, TheSisb requested changes

2020-12-11 16:33 UTC, ctecks commented on packages/paste-website/src/pages/content/product-style-guide/index.mdx
> +    the third person. Always check with the legal team if the content regards consent.</strong>.
Ah, my apologies, that's a leftover from the previous wording - I should have deleted that closing tag

2020-12-11 16:44 UTC, ctecks commented on packages/paste-website/src/pages/content/product-style-guide/index.mdx
> +    the third person. Always check with the legal team if the content regards consent.</strong>.
It's a leftover from the deleted section - the tag should have been deleted - sorry I didn't catch it - I changed it and committed again, should be ok now?

2020-12-18 15:51 UTC, TheSisb approved these changes

2020-12-18 16:53 UTC, merged